global:
  scrape_interval: 5s
  evaluation_interval: 5s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
  - job_name: "bib-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:30010"]
        labels:
          app: "bib-app"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.docker p