apiVersion: v1
kind: Service
metadata:
  name: biblioteca-svc
  namespace: biblioteca
spec:
  type: NodePort
  selector:
    app: biblioteca
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30010