apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: biblioteca
  name: biblioteca-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/d/Denise/Infnet/projeto_devops/biblioteca/k8s/data