apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: biblioteca
  name: biblioteca-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-storage