apiVersion: v1
kind: Service
metadata:
  name: bib-database-svc
  namespace: biblioteca
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432