apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  namespace: biblioteca
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana-container
          image: grafana/grafana
          imagePullPolicy: IfNotPresent