apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: biblioteca
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
        - targets: ["localhost:9090"]
          labels:
            app: "prometheus"
      - job_name: "bib-app"
        metrics_path: "/actuator/prometheus"
        static_configs:
        - targets: ["host.docker.internal:30010"]
          labels:
            app: "biblioteca"