apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: biblioteca
spec:
  storageClassName: local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /run/desktop/mnt/host/d/Denise/Infnet/projeto_devops/biblioteca/prometheus
    type: DirectoryOrCreate