--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-04-06 16:41:04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16658)
-- Name: livro; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.livro (
    id bigint NOT NULL,
    autor character varying(255) NOT NULL,
    titulo character varying(255) NOT NULL
);


ALTER TABLE public.livro OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16657)
-- Name: livro_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.livro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.livro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4890 (class 0 OID 16658)
-- Dependencies: 218
-- Data for Name: livro; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.livro (id, autor, titulo) FROM stdin;
1	Autor1	Titulo1
2	Autor2	Titulo2
3	Autor3	Titulo3
\.


--
-- TOC entry 4896 (class 0 OID 0)
-- Dependencies: 217
-- Name: livro_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.livro_id_seq', 3, true);


--
-- TOC entry 4743 (class 2606 OID 16664)
-- Name: livro livro_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.livro
    ADD CONSTRAINT livro_pkey PRIMARY KEY (id);


-- Completed on 2025-04-06 16:41:04

--
-- PostgreSQL database dump complete
--

